# Generated by Django 3.0.3 on 2020-07-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('hot_water_big', models.FloatField(blank=True, null=True, verbose_name='Горячая вода (Ванна)')),
                ('hot_water_small', models.FloatField(blank=True, null=True, verbose_name='Горячая вода (Туалет)')),
                ('cold_water_big', models.FloatField(blank=True, null=True, verbose_name='Холодная вода (Ванна)')),
                ('cold_water_small', models.FloatField(blank=True, null=True, verbose_name='Холодная вода (Туалет)')),
                ('electricity', models.FloatField(blank=True, null=True, verbose_name='Электроэнергия')),
                ('warm', models.FloatField(blank=True, null=True, verbose_name='Отопление')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('edited', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Отредактировано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='counters.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Показание счетчиков',
                'verbose_name_plural': 'Показания счетчиков',
                'ordering': ['-published'],
            },
        ),
    ]
