# Generated by Django 3.0.3 on 2020-07-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counters',
            name='rubric',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
