# Generated by Django 3.0.3 on 2020-07-17 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counters', '0002_auto_20200707_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counters',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Показание счетчиков', 'verbose_name_plural': 'Показания счетчиков'},
        ),
        migrations.AddField(
            model_name='counters',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counters',
            name='edited',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Отредактировано'),
        ),
    ]
