# Generated by Django 3.0.3 on 2020-07-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0003_auto_20200717_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counters',
            name='user',
        ),
    ]
